/*
 * Motor_Features.h - 库内部使用的算法编译开关入口
 *
 * 用户配置位置是 Platform/Motor/Platform_MotorFeatures.h。
 * 本文件负责将 Platform 的产品能力配置引入 Lib，并仅提供缺省兜底值。
 */

#pragma once

/* Platform 决定固件能力；cfg.observer 随后从已编译能力中选择实际反馈链。 */
#include "Platform_MotorFeatures.h"

#ifndef LIB_MOTOR_ENABLE_SENSOR
#define LIB_MOTOR_ENABLE_SENSOR 1
#endif

#ifndef LIB_MOTOR_ENABLE_STALL_PROTECTION
#define LIB_MOTOR_ENABLE_STALL_PROTECTION 1
#endif

#ifndef LIB_MOTOR_ENABLE_BATTERY_REGEN_PATH
#define LIB_MOTOR_ENABLE_BATTERY_REGEN_PATH 0
#endif

#ifndef LIB_MOTOR_ENABLE_BRAKE_RESISTOR
#define LIB_MOTOR_ENABLE_BRAKE_RESISTOR 0
#endif

#ifndef LIB_MOTOR_ENABLE_BRAKE_CHOPPER_CONTROL
#define LIB_MOTOR_ENABLE_BRAKE_CHOPPER_CONTROL 0
#endif

#ifndef LIB_MOTOR_ENABLE_BRAKE_ENERGY_FSM
#if LIB_MOTOR_ENABLE_BATTERY_REGEN_PATH || LIB_MOTOR_ENABLE_BRAKE_RESISTOR
#define LIB_MOTOR_ENABLE_BRAKE_ENERGY_FSM 1
#else
#define LIB_MOTOR_ENABLE_BRAKE_ENERGY_FSM 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_MECHANICAL_BRAKE
#define LIB_MOTOR_ENABLE_MECHANICAL_BRAKE 0
#endif

#ifndef LIB_MOTOR_ENABLE_IF_STARTUP
#define LIB_MOTOR_ENABLE_IF_STARTUP 0
#endif

#ifndef LIB_MOTOR_ENABLE_SMO
#define LIB_MOTOR_ENABLE_SMO 0
#endif

/* 当前 HFI/高级观测器尚无完整可执行路径，缺省禁止。 */
#ifndef LIB_MOTOR_ENABLE_HFI
#define LIB_MOTOR_ENABLE_HFI 0
#endif

#ifndef LIB_MOTOR_ENABLE_NONLINEAR_FLUX
#define LIB_MOTOR_ENABLE_NONLINEAR_FLUX 0
#endif
#ifndef LIB_MOTOR_ENABLE_LUENBERGER
#define LIB_MOTOR_ENABLE_LUENBERGER 0
#endif
#ifndef LIB_MOTOR_ENABLE_EKF
#define LIB_MOTOR_ENABLE_EKF 0
#endif

/*
 * 危险调试 API 仅供台架验证。库内部继续使用旧宏保护函数声明/定义，
 * 但是否开放由 Platform feature 统一决定。
 */
#ifndef LIB_MOTOR_ENABLE_ISR_LOAD_DIAGNOSTIC
#define LIB_MOTOR_ENABLE_ISR_LOAD_DIAGNOSTIC 0
#endif

#ifndef LIB_MOTOR_MAX_INSTANCES
#define LIB_MOTOR_MAX_INSTANCES 1
#endif

#ifndef LIB_MOTOR_NUMERIC_BACKEND_FLOAT32
#define LIB_MOTOR_NUMERIC_BACKEND_FLOAT32 1
#endif

#ifndef LIB_MOTOR_NUMERIC_BACKEND_FIXED_Q15
#define LIB_MOTOR_NUMERIC_BACKEND_FIXED_Q15 0
#endif

#ifndef LIB_MOTOR_NUMERIC_BACKEND_DUAL_TEST
#define LIB_MOTOR_NUMERIC_BACKEND_DUAL_TEST 0
#endif

#define LIB_MOTOR_NUMERIC_BACKEND_COUNT \
    (LIB_MOTOR_NUMERIC_BACKEND_FLOAT32 + \
     LIB_MOTOR_NUMERIC_BACKEND_FIXED_Q15 + \
     LIB_MOTOR_NUMERIC_BACKEND_DUAL_TEST)

#if LIB_MOTOR_NUMERIC_BACKEND_COUNT != 1
#error "Select exactly one LIB_MOTOR_NUMERIC_BACKEND_* option"
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_PWM_MANUAL
#define LIB_MOTOR_ENABLE_DEBUG_PWM_MANUAL 0
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_CURRENT_LOCK
#define LIB_MOTOR_ENABLE_DEBUG_CURRENT_LOCK 0
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_VF_CONTROL
#define LIB_MOTOR_ENABLE_DEBUG_VF_CONTROL 0
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_IF_CONTROL
#define LIB_MOTOR_ENABLE_DEBUG_IF_CONTROL 0
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_IF_SMO_OBSERVER
#define LIB_MOTOR_ENABLE_DEBUG_IF_SMO_OBSERVER 0
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_IF_HFI_OBSERVER
#define LIB_MOTOR_ENABLE_DEBUG_IF_HFI_OBSERVER 0
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_HFI_OBSERVER
#define LIB_MOTOR_ENABLE_DEBUG_HFI_OBSERVER 0
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_IF_ANY
#define LIB_MOTOR_ENABLE_DEBUG_IF_ANY \
    (LIB_MOTOR_ENABLE_DEBUG_IF_CONTROL || \
     LIB_MOTOR_ENABLE_DEBUG_IF_SMO_OBSERVER || \
     LIB_MOTOR_ENABLE_DEBUG_IF_HFI_OBSERVER)
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_HFI_ANY
#define LIB_MOTOR_ENABLE_DEBUG_HFI_ANY \
    (LIB_MOTOR_ENABLE_DEBUG_HFI_OBSERVER || \
     LIB_MOTOR_ENABLE_DEBUG_IF_HFI_OBSERVER)
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_PROFILE_ANY
#define LIB_MOTOR_ENABLE_DEBUG_PROFILE_ANY \
    (LIB_MOTOR_ENABLE_DEBUG_VF_CONTROL || LIB_MOTOR_ENABLE_DEBUG_IF_ANY)
#endif

#ifndef LIB_MOTOR_ENABLE_DEBUG_ANY
#define LIB_MOTOR_ENABLE_DEBUG_ANY \
    (LIB_MOTOR_ENABLE_DEBUG_PWM_MANUAL || \
     LIB_MOTOR_ENABLE_DEBUG_CURRENT_LOCK || \
     LIB_MOTOR_ENABLE_DEBUG_VF_CONTROL || \
     LIB_MOTOR_ENABLE_DEBUG_IF_ANY || \
     LIB_MOTOR_ENABLE_DEBUG_HFI_OBSERVER)
#endif

#ifndef LIB_MOTOR_ENABLE_SMO_OBSERVER
#define LIB_MOTOR_ENABLE_SMO_OBSERVER \
    (LIB_MOTOR_ENABLE_SMO || LIB_MOTOR_ENABLE_DEBUG_IF_SMO_OBSERVER)
#endif

/* ==================== Phase 2: 控制模式 / 前馈 / 流持仓 ==================== */
/* 缺省兜底: 若 Platform 未定义则按 0 处理 (即关闭)。 */

#ifndef LIB_MOTOR_ENABLE_TORQUE_CONTROL
#define LIB_MOTOR_ENABLE_TORQUE_CONTROL 0
#endif

#ifndef LIB_MOTOR_ENABLE_VELOCITY_CONTROL
#define LIB_MOTOR_ENABLE_VELOCITY_CONTROL 0
#endif

#ifndef LIB_MOTOR_ENABLE_POSITION_CONTROL
#define LIB_MOTOR_ENABLE_POSITION_CONTROL 0
#endif

#ifndef LIB_MOTOR_ENABLE_IMPEDANCE_CONTROL
#define LIB_MOTOR_ENABLE_IMPEDANCE_CONTROL 0
#endif

#ifndef LIB_MOTOR_ENABLE_VELOCITY_FEEDFORWARD
#define LIB_MOTOR_ENABLE_VELOCITY_FEEDFORWARD 0
#endif

#ifndef LIB_MOTOR_ENABLE_TORQUE_FEEDFORWARD
#define LIB_MOTOR_ENABLE_TORQUE_FEEDFORWARD 0
#endif

#ifndef LIB_MOTOR_ENABLE_STREAM_HOLD_WHEN_IDLE
#define LIB_MOTOR_ENABLE_STREAM_HOLD_WHEN_IDLE 0
#endif

#ifndef LIB_MOTOR_ENABLE_SETPOINT_FIFO_PLAYBACK
#define LIB_MOTOR_ENABLE_SETPOINT_FIFO_PLAYBACK 0
#endif

#ifndef LIB_MOTOR_SETPOINT_FIFO_CAPACITY
#ifdef MOTOR_BUILD_SETPOINT_FIFO_CAPACITY
#define LIB_MOTOR_SETPOINT_FIFO_CAPACITY MOTOR_BUILD_SETPOINT_FIFO_CAPACITY
#else
#define LIB_MOTOR_SETPOINT_FIFO_CAPACITY 16
#endif
#endif

#if LIB_MOTOR_SETPOINT_FIFO_CAPACITY < 1
#error "LIB_MOTOR_SETPOINT_FIFO_CAPACITY must be at least 1"
#endif

#ifndef LIB_MOTOR_ENABLE_FOC_CONTROL
#define LIB_MOTOR_ENABLE_FOC_CONTROL 1
#endif

#ifndef LIB_MOTOR_ENABLE_TRAP_CONTROL
#define LIB_MOTOR_ENABLE_TRAP_CONTROL 0
#endif

#ifndef LIB_MOTOR_ENABLE_HUMAN_READABLE_FAULT_DETAIL
#define LIB_MOTOR_ENABLE_HUMAN_READABLE_FAULT_DETAIL 1
#endif

#ifndef LIB_MOTOR_ENABLE_AUTO_IDENTIFY
#define LIB_MOTOR_ENABLE_AUTO_IDENTIFY 1
#endif

#ifndef LIB_MOTOR_ENABLE_FLYING_START
#define LIB_MOTOR_ENABLE_FLYING_START 0
#endif
