#pragma once

#ifndef USERAPP_ENABLE_SETPOINT_STREAM
#define USERAPP_ENABLE_SETPOINT_STREAM 1
#endif

#ifndef USERAPP_ENABLE_MOTION_COORDINATOR
#define USERAPP_ENABLE_MOTION_COORDINATOR 0
#endif

#ifndef USERAPP_ENABLE_ENERGY_COORDINATOR
#define USERAPP_ENABLE_ENERGY_COORDINATOR 0
#endif

#ifndef USERAPP_ENABLE_SYNC_COORDINATOR
#define USERAPP_ENABLE_SYNC_COORDINATOR 0
#endif

#if USERAPP_ENABLE_SYNC_COORDINATOR && !USERAPP_ENABLE_MOTION_COORDINATOR
#error "USERAPP_ENABLE_SYNC_COORDINATOR requires USERAPP_ENABLE_MOTION_COORDINATOR"
#endif
