/*
 * Platform_MotorFeatures.h - 当前产品固件需要编译的电机算法
 *
 * 本文件属于 Platform 与 Lib 之间的适配层：
 *   - BuildCfg 在 Platform 侧声明“这份固件编进去了哪些能力”
 *   - 本文件把这些能力映射成 Lib 侧使用的 LIB_MOTOR_ENABLE_xxx 宏
 *
 * 它与 Platform_MotorConfig*.h 中的 cfg.default_run_policy / 传感器配置
 * 不是同一层含义:
 *
 *   LIB_MOTOR_ENABLE_xxx  编译期能力开关:
 *     - 为 1: 相应算法代码允许被编入固件，可被 MotorCfg 选择
 *     - 为 0: 相应算法实例和执行分支会被裁掉或禁止使用，以节约 Flash/RAM
 *
 *   MotorCfg 运行配置:
 *     - 只能从已经编入固件的能力中选择当前电机的控制反馈链
 *     - 若误选未编译能力，static_assert / Motor_ConfigCheck 会报错
 *
 * 实现位置:
 *   - Lib/Motor/Public/Motor_Features.h 引入本文件，将开关传入电机库
 *   - Lib/Motor/Core/... 使用 #if 编译或裁剪观测器/分支
 *   - Platform_MotorConfig*.h 负责填写当前电机实际配置
 */

#pragma once

#include "BuildCfg/Platform_MotorBuildCfg.h"

#ifndef LIB_MOTOR_ENABLE_DANGEROUS_TEST_API
#ifdef MOTOR_BUILD_ENABLE_DANGEROUS_TEST_API
#define LIB_MOTOR_ENABLE_DANGEROUS_TEST_API 1
#else
#define LIB_MOTOR_ENABLE_DANGEROUS_TEST_API 0
#endif
#endif

#ifndef PLATFORM_MOTOR_ENABLE_TICK_PROFILING
#ifdef MOTOR_BUILD_ENABLE_TICK_PROFILING
#define PLATFORM_MOTOR_ENABLE_TICK_PROFILING 1
#else
#define PLATFORM_MOTOR_ENABLE_TICK_PROFILING 0
#endif
#endif

#ifndef LIB_MOTOR_MAX_INSTANCES
#define LIB_MOTOR_MAX_INSTANCES MOTOR_BUILD_MAX_INSTANCES
#endif

#ifndef LIB_MOTOR_ENABLE_SENSOR
#ifdef MOTOR_BUILD_ENABLE_SENSOR
#define LIB_MOTOR_ENABLE_SENSOR 1
#else
#define LIB_MOTOR_ENABLE_SENSOR 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_STALL_PROTECTION
#ifdef MOTOR_BUILD_ENABLE_STALL_PROTECTION
#define LIB_MOTOR_ENABLE_STALL_PROTECTION 1
#else
#define LIB_MOTOR_ENABLE_STALL_PROTECTION 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_IF_STARTUP
#ifdef MOTOR_BUILD_ENABLE_IF_STARTUP
#define LIB_MOTOR_ENABLE_IF_STARTUP 1
#else
#define LIB_MOTOR_ENABLE_IF_STARTUP 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_SMO
#ifdef MOTOR_BUILD_ENABLE_SMO
#define LIB_MOTOR_ENABLE_SMO 1
#else
#define LIB_MOTOR_ENABLE_SMO 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_HFI
#ifdef MOTOR_BUILD_ENABLE_HFI
#define LIB_MOTOR_ENABLE_HFI 1
#else
#define LIB_MOTOR_ENABLE_HFI 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_NONLINEAR_FLUX
#ifdef MOTOR_BUILD_ENABLE_NONLINEAR_FLUX
#define LIB_MOTOR_ENABLE_NONLINEAR_FLUX 1
#else
#define LIB_MOTOR_ENABLE_NONLINEAR_FLUX 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_LUENBERGER
#ifdef MOTOR_BUILD_ENABLE_LUENBERGER
#define LIB_MOTOR_ENABLE_LUENBERGER 1
#else
#define LIB_MOTOR_ENABLE_LUENBERGER 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_EKF
#ifdef MOTOR_BUILD_ENABLE_EKF
#define LIB_MOTOR_ENABLE_EKF 1
#else
#define LIB_MOTOR_ENABLE_EKF 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_BRAKE_ENERGY_FSM
#if defined(MOTOR_BUILD_ENABLE_BATTERY_REGEN_PATH) || defined(MOTOR_BUILD_ENABLE_BRAKE_RESISTOR)
#define LIB_MOTOR_ENABLE_BRAKE_ENERGY_FSM 1
#else
#define LIB_MOTOR_ENABLE_BRAKE_ENERGY_FSM 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_BATTERY_REGEN_PATH
#ifdef MOTOR_BUILD_ENABLE_BATTERY_REGEN_PATH
#define LIB_MOTOR_ENABLE_BATTERY_REGEN_PATH 1
#else
#define LIB_MOTOR_ENABLE_BATTERY_REGEN_PATH 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_BRAKE_RESISTOR
#ifdef MOTOR_BUILD_ENABLE_BRAKE_RESISTOR
#define LIB_MOTOR_ENABLE_BRAKE_RESISTOR 1
#else
#define LIB_MOTOR_ENABLE_BRAKE_RESISTOR 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_BRAKE_CHOPPER_CONTROL
#ifdef MOTOR_BUILD_ENABLE_BRAKE_CHOPPER_CONTROL
#define LIB_MOTOR_ENABLE_BRAKE_CHOPPER_CONTROL 1
#else
#define LIB_MOTOR_ENABLE_BRAKE_CHOPPER_CONTROL 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_MECHANICAL_BRAKE
#ifdef MOTOR_BUILD_ENABLE_MECHANICAL_BRAKE
#define LIB_MOTOR_ENABLE_MECHANICAL_BRAKE 1
#else
#define LIB_MOTOR_ENABLE_MECHANICAL_BRAKE 0
#endif
#endif

/* ==================== Phase 2: 控制模式 / 前馈 / 流持仓 ==================== */

#ifndef LIB_MOTOR_ENABLE_TORQUE_CONTROL
#ifdef MOTOR_BUILD_ENABLE_TORQUE_CONTROL
#define LIB_MOTOR_ENABLE_TORQUE_CONTROL 1
#else
#define LIB_MOTOR_ENABLE_TORQUE_CONTROL 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_VELOCITY_CONTROL
#ifdef MOTOR_BUILD_ENABLE_VELOCITY_CONTROL
#define LIB_MOTOR_ENABLE_VELOCITY_CONTROL 1
#else
#define LIB_MOTOR_ENABLE_VELOCITY_CONTROL 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_POSITION_CONTROL
#ifdef MOTOR_BUILD_ENABLE_POSITION_CONTROL
#define LIB_MOTOR_ENABLE_POSITION_CONTROL 1
#else
#define LIB_MOTOR_ENABLE_POSITION_CONTROL 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_IMPEDANCE_CONTROL
#ifdef MOTOR_BUILD_ENABLE_IMPEDANCE_CONTROL
#define LIB_MOTOR_ENABLE_IMPEDANCE_CONTROL 1
#else
#define LIB_MOTOR_ENABLE_IMPEDANCE_CONTROL 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_VELOCITY_FEEDFORWARD
#ifdef MOTOR_BUILD_ENABLE_VELOCITY_FEEDFORWARD
#define LIB_MOTOR_ENABLE_VELOCITY_FEEDFORWARD 1
#else
#define LIB_MOTOR_ENABLE_VELOCITY_FEEDFORWARD 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_TORQUE_FEEDFORWARD
#ifdef MOTOR_BUILD_ENABLE_TORQUE_FEEDFORWARD
#define LIB_MOTOR_ENABLE_TORQUE_FEEDFORWARD 1
#else
#define LIB_MOTOR_ENABLE_TORQUE_FEEDFORWARD 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_STREAM_HOLD_WHEN_IDLE
#ifdef MOTOR_BUILD_ENABLE_STREAM_HOLD_WHEN_IDLE
#define LIB_MOTOR_ENABLE_STREAM_HOLD_WHEN_IDLE 1
#else
#define LIB_MOTOR_ENABLE_STREAM_HOLD_WHEN_IDLE 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_SETPOINT_FIFO_PLAYBACK
#ifdef MOTOR_BUILD_ENABLE_SETPOINT_FIFO_PLAYBACK
#define LIB_MOTOR_ENABLE_SETPOINT_FIFO_PLAYBACK 1
#else
#define LIB_MOTOR_ENABLE_SETPOINT_FIFO_PLAYBACK 0
#endif
#endif

#ifndef LIB_MOTOR_SETPOINT_FIFO_CAPACITY
#define LIB_MOTOR_SETPOINT_FIFO_CAPACITY MOTOR_BUILD_SETPOINT_FIFO_CAPACITY
#endif

/* ==================== [13] 控制拓扑能力 ==================== */

#ifndef LIB_MOTOR_ENABLE_FOC_CONTROL
#ifdef MOTOR_BUILD_ENABLE_FOC_CONTROL
#define LIB_MOTOR_ENABLE_FOC_CONTROL 1
#else
#define LIB_MOTOR_ENABLE_FOC_CONTROL 0
#endif
#endif

#ifndef LIB_MOTOR_ENABLE_TRAP_CONTROL
#ifdef MOTOR_BUILD_ENABLE_TRAP_CONTROL
#define LIB_MOTOR_ENABLE_TRAP_CONTROL 1
#else
#define LIB_MOTOR_ENABLE_TRAP_CONTROL 0
#endif
#endif

/* ==================== [14] 调试诊断字符串 ==================== */

#ifndef LIB_MOTOR_ENABLE_HUMAN_READABLE_FAULT_DETAIL
#ifdef MOTOR_BUILD_ENABLE_HUMAN_READABLE_FAULT_DETAIL
#define LIB_MOTOR_ENABLE_HUMAN_READABLE_FAULT_DETAIL 1
#else
#define LIB_MOTOR_ENABLE_HUMAN_READABLE_FAULT_DETAIL 0
#endif
#endif

/* ==================== [15] 参数自动辨识 ==================== */

#ifndef LIB_MOTOR_ENABLE_AUTO_IDENTIFY
#ifdef MOTOR_BUILD_ENABLE_AUTO_IDENTIFY
#define LIB_MOTOR_ENABLE_AUTO_IDENTIFY 1
#else
#define LIB_MOTOR_ENABLE_AUTO_IDENTIFY 0
#endif
#endif

/* ==================== [16] 顺逆风启动 ==================== */

#ifndef LIB_MOTOR_ENABLE_FLYING_START
#ifdef MOTOR_BUILD_ENABLE_FLYING_START
#define LIB_MOTOR_ENABLE_FLYING_START 1
#else
#define LIB_MOTOR_ENABLE_FLYING_START 0
#endif
#endif
